language: cpp
dist: focal

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      
before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -B_build -DBUILD_TESTING=ON -DCOVERAGE=1 .
  - cmake --build _build --target asm_test
  - cd _build && ctest
  
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*
